[package]
name = "evm-simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.2.1"
hex = "0.4.3"
dotenv = "0.15.0"
tokio = { version = "1.29.0", features = ["full"] }
tokio-stream = { version = "0.1", features = ['sync'] }
futures = "0.3.5"
async-trait = "0.1.64"
anyhow = "1.0.70"
serde = "1.0.145"
serde_json = "1.0"
itertools = "0.11.0"

cfmms = "*"
ethers-flashbots = { git = "https://github.com/onbjerg/ethers-flashbots"}
ethers = { version = "2.0", features = ["abigen", "ws"]}
ethers-core = "2.0"
ethers-providers = "2.0"
ethers-contract = "2.0"
foundry-evm = { git = "https://github.com/solidquant/foundry.git", branch = "version-fix" }
anvil = { git = "https://github.com/solidquant/foundry.git", branch = "version-fix" }
eth-encode-packed = "0.1.0"

colored = "2.0.0"
log = "0.4.17"
indicatif = "0.17.5"
indoc = "2"
fern = {version = "0.6.2", features = ["colored"]}
chrono = "0.4.23"
csv = "1.2.2"